"""empty message

Revision ID: 6554a1f27c92
Revises: 
Create Date: 2020-03-19 17:07:48.245995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6554a1f27c92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acting_in',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['Actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.id'], ),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id')
    )
    # ### end Alembic commands ###
        # populate Actors
    op.execute("insert into \"Actors\"(name,age,email,salary)\
                values('ALi','30','ali@gmail.com','5000');")
    op.execute("insert into \"Actors\"(name,age,email,salary)\
                values('Ahmed','30','Ahmed@gmail.com','7000');")
    op.execute("insert into \"Actors\"(name,age,email,salary)\
                values('Noha','38','Noha@gmail.com','1000');")

    #popluate Movies
    op.execute("insert into \"Movies\"(name,length,genre)\
                values('GoGo','1.3','Action');")
    op.execute("insert into \"Movies\"(name,length,genre)\
                values('alo','10.5','Thriler');")
    op.execute("insert into \"Movies\"(name,length,genre)\
                values('matygy','1.9','Romance');")

    #popluate acting_in
    op.execute("insert into \"acting_in\"(actor_id,movie_id)\
                values('1','1');")
    op.execute("insert into \"acting_in\"(actor_id,movie_id)\
                values('1','2');")
    op.execute("insert into \"acting_in\"(actor_id,movie_id)\
                values('1','3');")
    op.execute("insert into \"acting_in\"(actor_id,movie_id)\
                values('2','3');")
    op.execute("insert into \"acting_in\"(actor_id,movie_id)\
                values('2','1');")
    op.execute("insert into \"acting_in\"(actor_id,movie_id)\
                values('3','1');")
    op.execute("insert into \"acting_in\"(actor_id,movie_id)\
                values('3','2');")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acting_in')
    op.drop_table('Movies')
    op.drop_table('Actors')
    # ### end Alembic commands ###
